#Script for merging questionnaire files from qualtrics to make a master 
# last updated - 7/20/2018

setwd("/Volumes/Space/ELFK/Data_Entry/Questionnaires/R_Cleaning_Qualtrics_Data/QUALTRICS_CLEANED_IN_R/")

#add all questionnaires you want to merge
#add any new questionnaire scripts 
q1 <- read.csv("Qualtrics_Cleaned_in_R_AIOI_Questionnaire.csv")
q2 <- read.csv("Qualtrics_Cleaned_in_R_BDI_Questionnaire.csv") 
q3 <- read.csv("Qualtrics_Cleaned_in_R_Caregiving_Questionnaire.csv")
q4 <- read.csv("Qualtrics_Cleaned_in_R_CRPR_Questionnaire.csv")
q5 <- read.csv("Qualtrics_Cleaned_in_R_GRIT_Questionnaire.csv")
q6 <- read.csv("Qualtrics_Cleaned_in_R_Parent_Questionnaire.csv")
q7 <- read.csv("Qualtrics_Cleaned_in_R_Peterson_Female_Questionnaire_new.csv")
q8 <- read.csv("Qualtrics_Cleaned_in_R_Peterson_Male_Questionnaire_new.csv")
q9 <- read.csv("Qualtrics_Cleaned_in_R_SCARED_Questionnaire.csv")
q10 <- read.csv("Qualtrics_Cleaned_in_R_SecurityScale_Questionnaire.csv")
q11 <- read.csv("Qualtrics_Cleaned_in_R_DSM_Questionnaire.csv")
q12 <- read.csv("Qualtrics_Cleaned_in_R_HigginsMotivation_Questionnaire.csv")
q13 <- read.csv("Qualtrics_Cleaned_in_R_IF_Questionnaire.csv")
q14 <- read.csv("Qualtrics_Cleaned_in_R_Relationship_Problems_Questionnaire.csv")
q15 <- read.csv("Qualtrics_Cleaned_in_R_RADS_Questionnaire.csv")
q16 <- read.csv("Qualtrics_Cleaned_in_R_DSMPIParents_Questionnaire.csv")
q17 <- read.csv("Qualtrics_Cleaned_in_R_Friendship_Questionnaire.csv")
q18 <- read.csv("Qualtrics_Cleaned_in_R_Adoption_Questionnaire.csv")
q19 <- read.csv("Qualtrics_Cleaned_in_R_LEQ_Questionnaire.csv")
q20 <- read.csv("Qualtrics_Cleaned_in_R_DEM_Questionnaire_FINAL.csv")
#MERGE INTO ONE VARIABLE
#if you add new questionnaire scripts, add to this.
df_merged1 <-merge(q1, q2, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged1)
df_merged2 <- merge(df_merged1,q3, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged2)
df_merged3 <- merge(df_merged2, q4, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged3)
df_merged4 <- merge(df_merged3, q5, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged4)
df_merged5 <- merge(df_merged4, q6, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged5)
df_merged6 <- merge(df_merged5, q7, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged6)
df_merged7 <- merge(df_merged6, q8, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged7)
df_merged8 <- merge(df_merged7, q9, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged8)
df_merged9 <- merge(df_merged8, q10, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged9)
df_merged10 <- merge(df_merged9, q11, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged10)
df_merged11 <- merge(df_merged10, q12, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged11)
df_merged12 <- merge(df_merged11, q13, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged12)
df_merged13 <- merge(df_merged12, q14, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged13)
df_merged14 <- merge(df_merged13, q15, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged14)
df_merged15 <- merge(df_merged14, q16, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged15)
df_merged16 <- merge(df_merged15, q17, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged16)
df_merged17 <- merge(df_merged16, q18, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged17)
df_merged18 <- merge(df_merged17, q19, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged18)
df_merged19 <- merge(df_merged18, q20, by = "IDENT_SUBID", all = TRUE)
nrow(df_merged19)
#Save output
write.csv(df_merged19, "ELFK_Qualtrics_merged_r_July_20_2018_fixed.csv", row.names =  FALSE)
