---
title: "SS scaling"
author: "Ian Douglas"
date: "3/8/2019"
output: html_document
---
###Data exported from qualtrics 3/8/2019
#Load tidied data
```{r}
rm(list=ls()) #remove all objects in the environment
df <- read_rds("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/02 Tidied/QUALTRICS/Children/SS_tidy.Rds")
```   


#Code subscales
```{r}
#Recode all binary variables to a=0 and b=1, rather than a=1 and b=2.
# (every other variable from 1A to 15A)
df1 <- df %>% mutate_at(seq(from=3,to=31,by=2), function(x) (x-1))
#Prepare a function to recode the 4 combinations of paired responses 
#to questions 1A x 1B, through 15A x 15B.
#x is the binary variable ending in A (a was coded 1, b = 2), and y is the
#variable of the same number that is coded 1, 2, 3, or 4 in the raw data.

SS.recode = function(x,y) {
  char <- character()
  for (i in 1:length(x)) {
    char[i] <- paste0(x[i],y[i])
  }
output <- as.numeric(recode(char, 
                            "01" = 4L, "02" = 4L, 
                            "03" = 3L, "04" = 3L, 
                            "14" = 2L, "13" = 2L, 
                            "12" = 1L, "11" = 1L,
                            .default = NA_integer_))
}
#Create function to do the same, but reverse code the output:
SS.reverse.recode = function(x,y) {
  char <- character()
  for (i in 1:length(x)) {
    char[i] <- paste0(x[i],y[i])
  }
output <- as.numeric(recode(char, 
                            "11" = 4L, "12" = 4L, 
                            "13" = 3L, "14" = 3L, 
                            "04" = 2L, "03" = 2L, 
                            "02" = 1L, "01" = 1L,
                            .default = NA_integer_))
}

#Create new variables from the 15 pairs of numeric variables:
df1$SS_NEW_1_SCORE <- SS.recode(df1$SS_NEW_1A, df1$SS_NEW_1B)
df1$SS_NEW_2_SCORE <- SS.reverse.recode(df1$SS_NEW_2A, df1$SS_NEW_2B) #reverse
df1$SS_NEW_3_SCORE <- SS.recode(df1$SS_NEW_3A, df1$SS_NEW_3B)
df1$SS_NEW_4_SCORE <- SS.recode(df1$SS_NEW_4A, df1$SS_NEW_4B)
df1$SS_NEW_5_SCORE <- SS.reverse.recode(df1$SS_NEW_5A, df1$SS_NEW_5B) #reverse
df1$SS_NEW_6_SCORE <- SS.reverse.recode(df1$SS_NEW_6A, df1$SS_NEW_6B) #reverse
df1$SS_NEW_7_SCORE <- SS.reverse.recode(df1$SS_NEW_7A, df1$SS_NEW_7B) #reverse
df1$SS_NEW_8_SCORE <- SS.reverse.recode(df1$SS_NEW_8A, df1$SS_NEW_8B) #reverse
df1$SS_NEW_9_SCORE <- SS.recode(df1$SS_NEW_9A, df1$SS_NEW_9B)
df1$SS_NEW_10_SCORE <- SS.recode(df1$SS_NEW_10A, df1$SS_NEW_10B)
df1$SS_NEW_11_SCORE <- SS.reverse.recode(df1$SS_NEW_11A, df1$SS_NEW_11B) #reverse
df1$SS_NEW_12_SCORE <- SS.reverse.recode(df1$SS_NEW_12A, df1$SS_NEW_12B) #reverse
df1$SS_NEW_13_SCORE <- SS.recode(df1$SS_NEW_13A, df1$SS_NEW_13B)
df1$SS_NEW_14_SCORE <- SS.reverse.recode(df1$SS_NEW_14A, df1$SS_NEW_14B) #reverse
df1$SS_NEW_15_SCORE <- SS.recode(df1$SS_NEW_15A, df1$SS_NEW_15B)
```
   
   #Code subscale variables and total mean
```{r}
df2 <- df1 %>% group_by(IDENT_SUBID) %>% 
  mutate(SS_NEW_AVAILABILITY_MEAN = mean(c(SS_NEW_2_SCORE, 
                                                   SS_NEW_4_SCORE, 
                                                   SS_NEW_7_SCORE, 
                                                   SS_NEW_8_SCORE,
                                                   SS_NEW_10_SCORE),
                                                 na.rm=TRUE),
                      SS_NEW_AVAILABILITY_SUM = mean(c(SS_NEW_2_SCORE, 
                                                   SS_NEW_4_SCORE, 
                                                   SS_NEW_7_SCORE, 
                                                   SS_NEW_8_SCORE,
                                                   SS_NEW_10_SCORE),
                                                 na.rm=TRUE)*5,
                      SS_NEW_RELYSTRESS_MEAN = mean(c(SS_NEW_3_SCORE, 
                                                      SS_NEW_6_SCORE, 
                                                      SS_NEW_11_SCORE, 
                                                      SS_NEW_13_SCORE, 
                                                      SS_NEW_14_SCORE, 
                                                      SS_NEW_15_SCORE), 
                                                    na.rm = TRUE),
                      SS_NEW_RELYSTRESS_SUM = mean(c(SS_NEW_3_SCORE, 
                                                     SS_NEW_6_SCORE, 
                                                     SS_NEW_11_SCORE, 
                                                     SS_NEW_13_SCORE, 
                                                     SS_NEW_14_SCORE, 
                                                     SS_NEW_15_SCORE), 
                                                   na.rm = TRUE)*6,
                      SS_NEW_COMMUNICATION_MEAN = mean(c(SS_NEW_1_SCORE,
                                                         SS_NEW_5_SCORE, 
                                                         SS_NEW_9_SCORE, 
                                                         SS_NEW_12_SCORE),
                                                       na.rm=TRUE),
                      SS_NEW_COMMUNICATION_SUM = mean(c(SS_NEW_1_SCORE,
                                                         SS_NEW_5_SCORE, 
                                                         SS_NEW_9_SCORE, 
                                                         SS_NEW_12_SCORE),
                                                       na.rm=TRUE)*4)
#Now the total mean
df3 <- df2 %>% group_by(IDENT_SUBID) %>% 
  mutate(SS_NEW_TOTAL_MEAN = mean(c(SS_NEW_1_SCORE, SS_NEW_2_SCORE,
                                    SS_NEW_3_SCORE, SS_NEW_4_SCORE,
                                    SS_NEW_5_SCORE, SS_NEW_6_SCORE,
                                    SS_NEW_7_SCORE, SS_NEW_8_SCORE,
                                    SS_NEW_9_SCORE, SS_NEW_10_SCORE,
                                    SS_NEW_11_SCORE, SS_NEW_12_SCORE,
                                    SS_NEW_13_SCORE, SS_NEW_14_SCORE,
                                    SS_NEW_15_SCORE), na.rm = TRUE))
#And the total mean continuous vairable:
df3 <- df3 %>% group_by(IDENT_SUBID) %>% 
  mutate(SS_NEW_TOTAL_SUM = SS_NEW_TOTAL_MEAN*15)
```
   
   #Merge in PACCT participants' data
```{r}
pdf <- read.csv("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/01 Raw/PACCT/pacct.csv", 
              stringsAsFactors=FALSE)

#extract variables pertaining to the SS (and the date)
pdf1 <- pdf %>% select(DEM_1_DATESESS1,IDENT_SUBID,starts_with("SS_"))

#process the dates exactly as was done during tidying of the raw qualtrics data
pdf2 <- pdf1 %>% 
  #mutate_at(1, function(x) as.character(x)) %>%
  #mutate_at(1, function(x) strtrim(x,10)) %>%
  mutate_at(1, function(x) as.Date(x, format = "%Y-%m-%d"))

##(View the data to ensure the variables were in the same order)
#View(pdf1)

#Synchronize variable names
pdf3 <- as.data.frame(pdf2)
names(pdf3) <- names(df3)
# MERGE with rest of participants
df4 <- as.data.frame(rbind(as.data.frame(df3),pdf3))
```


#Lastly, add indexing variable for subjects with incomplete data
```{r}
# After discussion with Michelle V. and Bridget C., flag participants who
# are missing 20% or more of their data on the raw questionnaire
# and create "adjusted" mean variables that produce NA for such cases.

#calculate for each participant the percentage of NA in their data
index <- numeric()
for (i in 1:nrow(df4)) {
  index[i] <- sum(filter(df4,IDENT_SUBID == df4$IDENT_SUBID[i])[,3:32] %>%
                    is.na())/length(3:32)
}
#binarize it
df4$SS_FULL_DATAYN <- ifelse(index < .2, 1, 0)
#Now transform our two means accordingly
df4$SS_NEW_TOTAL_MEAN_ADJ <- ifelse(df4$SS_FULL_DATAYN==1,df4$SS_NEW_TOTAL_MEAN, NA)
df4$SS_NEW_TOTAL_SUM_ADJ <- ifelse(df4$SS_FULL_DATAYN==1,df4$SS_NEW_TOTAL_SUM, NA)
```

#check dimensions of final product:
```{r}
dim(df4)
#output should read 135 58 using 3/8/2019 data as above.
```

#check classes of variables:
```{r}
classes <- NULL
for (i in names(df4)) {
    classes[i]<-(select(df4,i))[[1]] %>% class()
}
table(classes)
###Output should read:
## classes
## character      Date   numeric 
##         1         1        56 
```
#Write out finalized, scaled data.
```{r}
write_rds(df4,"/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/03 Scored/R/SS.rds")
#Convert to character before writing out .csv and .sav
library(haven)
df5<-as.data.frame(lapply(df4,as.character),stringsAsFactors=F)
write.csv(df5, "/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/03 Scored/csv/SS_final.csv", row.names = FALSE)
write_sav(df5, "/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/03 Scored/SPSS/SS_final.sav")
```
