---
title: "STAI Trait Scoring"
author: "Ian Douglas"
date: "5/29/2019"
output: html_document
---
#read in tidy data
```{r}
rm(list=ls())
suppressPackageStartupMessages(library(tidyverse))
df<-readRDS("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/02 Tidied/QUALTRICS/Parent/R/STAI_trait_tidy.rds")
```
#delete the age, sex, and date columns
```{r}
df1 <- df[,c("IDENT_SUBID", names(df)[grep("[0-9]$",names(df))])]
```

reverse code select variables
```{r}
reverse.var <- function(x) {5-x} #range 1 to 4 for all variables

df2 <- df1 %>% 
  group_by(IDENT_SUBID) %>%
  mutate(PARENT_STAI_TRAIT_1R = reverse.var(PARENT_STAI_TRAIT_1),
         PARENT_STAI_TRAIT_3R = reverse.var(PARENT_STAI_TRAIT_3),
         PARENT_STAI_TRAIT_6R = reverse.var(PARENT_STAI_TRAIT_6),
         PARENT_STAI_TRAIT_7R = reverse.var(PARENT_STAI_TRAIT_7),
         PARENT_STAI_TRAIT_10R= reverse.var(PARENT_STAI_TRAIT_10),
         PARENT_STAI_TRAIT_13R= reverse.var(PARENT_STAI_TRAIT_13),
         PARENT_STAI_TRAIT_14R= reverse.var(PARENT_STAI_TRAIT_14),
         PARENT_STAI_TRAIT_16R= reverse.var(PARENT_STAI_TRAIT_16),
         PARENT_STAI_TRAIT_19R= reverse.var(PARENT_STAI_TRAIT_19))
```

Code the subscale variables
```{r}
df3 <- df2 %>%
  mutate(PARENT_STAI_TRAIT_ANX_SUM = mean(
    c(PARENT_STAI_TRAIT_1R, PARENT_STAI_TRAIT_2, PARENT_STAI_TRAIT_3R,
      PARENT_STAI_TRAIT_4, PARENT_STAI_TRAIT_5, PARENT_STAI_TRAIT_6R,
      PARENT_STAI_TRAIT_7R, PARENT_STAI_TRAIT_8, PARENT_STAI_TRAIT_9,
      PARENT_STAI_TRAIT_10R, PARENT_STAI_TRAIT_11, PARENT_STAI_TRAIT_12,
      PARENT_STAI_TRAIT_13R, PARENT_STAI_TRAIT_14R, PARENT_STAI_TRAIT_15,
      PARENT_STAI_TRAIT_16R, PARENT_STAI_TRAIT_17, PARENT_STAI_TRAIT_18,
      PARENT_STAI_TRAIT_19R, PARENT_STAI_TRAIT_20), 
    na.rm = TRUE)*20) %>%
  ungroup()
```
Write out the scored STAI-TRAIT data
```{r}
saveRDS(df3, "/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/03 Scored/R/STAI_trait_scored.rds")
```

