---
title: "DSM child scoring"
author: "Ian Douglas"
date: "5/31/2019"
output: html_document
---

#Read in tidy .Rds
```{r}
rm(list = ls())
df<-readRDS("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/02 Tidied/QUALTRICS/Children/R/DSM_C_tidy.rds")
```

#Code subscale variables
```{r}
df$DSM_SOMATIC_C <- ifelse((df$DSM_1_C >= 2) | (df$DSM_2_C >= 2), 1, 0)
df$DSM_SLEEP_C <- ifelse(df$DSM_3_C >= 2, 1, 0)
df$DSM_INATTEN_C <- ifelse(df$DSM_4_C >= 2, 1, 0)
df$DSM_DEPRESS_C <- ifelse((df$DSM_5_C >= 2) | (df$DSM_6_C >= 2), 1, 0)
df$DSM_ANGR_IRRIT_C <- ifelse((df$DSM_7_C >= 2) | (df$DSM_8_C >= 2), 1, 0)
df$DSM_MANIA_C <- ifelse((df$DSM_9_C >= 2) | (df$DSM_10_C >= 2), 1, 0)
df$DSM_ANX_C <- ifelse((df$DSM_11_C >= 2) | (df$DSM_12_C >= 2) | (df$DSM_13_C >= 2), 1, 0)
df$DSM_CSYCHOSIS_C <- ifelse((df$DSM_14_C >= 2) | (df$DSM_15_C >= 2), 1, 0)
df$DSM_REPET_THGHT_C <- ifelse((df$DSM_16_C >= 2) | (df$DSM_17_C >= 2) |
                                 (df$DSM_18_C >= 2) | (df$DSM_19_C >= 2), 1, 0)
df$DSM_SUBSTUSE_C <- ifelse((df$DSM_20_C == 1) | (df$DSM_21_C == 1) |
                              (df$DSM_22_C == 1) | (df$DSM_23_C == 1), 1, 0)
```

#Done!
Write out finalized data.
```{r}
saveRDS(df, "/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/03 Scored/R/DSM_C final.rds")
```
