---
title: "PPDS_-only-_Merge"
author: "Ian Douglas"
date: "5/22/2019"
output: html_document
---
#load in the 4 data frames with PPDS data
```{r}
rm(list=ls())
ppds.fc <- readRDS("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/03 Scored/R/PPDS_fem_child.rds")
ppds.mc <- readRDS("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/03 Scored/R/PPDS_mal_child.rds")
ppds.fp <- readRDS("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/03 Scored/R/PPDS_fem_parent.rds")
ppds.mp <- readRDS("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/03 Scored/R/PPDS_mal_parent.rds")
```
#Create master list of unique IDs for each gender
```{r}
all.ids.female <- unique(c(ppds.fc$IDENT_SUBID, ppds.fp$IDENT_SUBID))
all.ids.male <- unique(c(ppds.mc$IDENT_SUBID, ppds.mp$IDENT_SUBID))
```
#create empty data frames to capture the desired columns (one for each gender)
```{r}
#female frame will have columns for 4 variables, plus ID, plus gender
ppds.fem <- data.frame("IDENT_SUBID" = all.ids.female, 
                       "gender" = rep("F",times=length(all.ids.female)),
                       matrix(rep(NA,times = 4*length(all.ids.female)),ncol=4,
                              dimnames = list(NULL, c(
                                "PPDS_F_6_MENSTRU_C", "PPDS_F_STAGE_C",
                                "PPDS_F_6_MENSTRU_P","PPDS_F_STAGE_P"))))
#make sure al data types are correct
ppds.fem[1:2] <- lapply(ppds.fem[1:2], as.character)
ppds.fem[3:6] <- lapply(ppds.fem[3:6], function(x) as.numeric(as.character(x)))
#female frame will have columns for 2 variables, plus ID, plus gender
ppds.male <- data.frame("IDENT_SUBID" = all.ids.male, 
                       "gender" = rep("M",times=length(all.ids.male)),
                       matrix(rep(NA,times = 2*length(all.ids.male)),ncol=2,
                              dimnames = list(NULL, c(
                                "PPDS_M_STAGE_C","PPDS_M_STAGE_P"))))
#make the first two columns datatype character for simplification
ppds.male[1:2] <- lapply(ppds.male[1:2], as.character)
ppds.male[3:4] <- lapply(ppds.male[3:4], function(x) as.numeric(as.character(x)))
```

#In a loop fill in the desired data.
```{r}
#female data frame:
for (i in seq_along(ppds.fem$IDENT_SUBID)) {
  who <- ppds.fem$IDENT_SUBID[i] #the row of the master list
  where.c <- which(ppds.fc$IDENT_SUBID %in% who) #the index for the kid
  where.p <- which(ppds.fp$IDENT_SUBID %in% who) #the index for the parent
  any.TF.c <- any(ppds.fc$IDENT_SUBID %in% who) #binary flag for the kid
  any.TF.p <- any(ppds.fp$IDENT_SUBID %in% who) #binary flag for the parent
  if (any.TF.c) {
    ppds.fem$PPDS_F_6_MENSTRU_C[i] <- ppds.fc$PPDS_F_6_MENSTRU_C[where.c]
    ppds.fem$PPDS_F_STAGE_C[i] <- ppds.fc$PPDS_F_STAGE_C[where.c]
  } else {
    ppds.fem$PPDS_F_6_MENSTRU_C[i] <- NA
    ppds.fem$PPDS_F_STAGE_C[i] <- NA
  }
  if (any.TF.p) {
    ppds.fem$PPDS_F_6_MENSTRU_P[i] <- ppds.fp$PPDS_F_6_MENSTRU_P[where.p]
    ppds.fem$PPDS_F_STAGE_P[i] <- ppds.fp$PPDS_F_STAGE_P[where.p]
  } else {
    ppds.fem$PPDS_F_6_MENSTRU_P[i] <- NA
    ppds.fem$PPDS_F_STAGE_P[i] <- NA
  }
}

#male data frame:
for (i in seq_along(ppds.male$IDENT_SUBID)) {
  who.male <- ppds.male$IDENT_SUBID[i] #the row of the master list
  where.c.male <- which(ppds.mc$IDENT_SUBID %in% who.male) #the index for the kid
  where.p.male <- which(ppds.mp$IDENT_SUBID %in% who.male) #the index for the parent
  any.TF.c.male <- any(ppds.mc$IDENT_SUBID %in% who.male) #binary flag for the kid
  any.TF.p.male <- any(ppds.mp$IDENT_SUBID %in% who.male) #binary flag for the parent
  if (any.TF.c.male) {
    ppds.male$PPDS_M_STAGE_C[i] <- ppds.mc$PPDS_M_STAGE_C[where.c.male]
  } else {
    ppds.male$PPDS_M_STAGE_C[i] <- NA
  }
  if (any.TF.p.male) {
    ppds.male$PPDS_M_STAGE_P[i] <- ppds.mp$PPDS_M_STAGE_P[where.p.male]
  } else {
    ppds.male$PPDS_M_STAGE_P[i] <- NA
  }
}
```
#Combine into one spreadsheet (not finalized data, because sub-items omitted)
```{r}
#prep before loop
master.list <- unique(c(ppds.fem$IDENT_SUBID, ppds.male$IDENT_SUBID))

ppds.master <- data.frame("IDENT_SUBID" = master.list,
                          matrix(rep(0,times = 7*length(master.list)),ncol=7,
                                 dimnames = list(NULL, c("gender",
                                "PPDS_F_6_MENSTRU_C", "PPDS_F_STAGE_C",
                                "PPDS_F_6_MENSTRU_P", "PPDS_F_STAGE_P",
                                "PPDS_M_STAGE_C", "PPDS_M_STAGE_P"))))
#make sure all data types are correct
ppds.fem[1:2] <- lapply(ppds.fem[1:2], as.character)
ppds.fem[3:6] <- lapply(ppds.fem[3:6], function(x) as.numeric(as.character(x)))
ppds.male[1:2] <- lapply(ppds.male[1:2], as.character)
ppds.male[3:4] <- lapply(ppds.male[3:4], function(x) as.numeric(as.character(x)))
```
#Run the loop
```{r}
for (i in seq_along(master.list)) {
  who <- master.list[i]
  female.TF <- any(ppds.fem$IDENT_SUBID == who)
  male.TF <- any(ppds.male$IDENT_SUBID == who)
  if (female.TF) {
    ppds.master$gender[i] <- "F"
    ppds.master[i, 3:6] <- ppds.fem[ppds.fem$IDENT_SUBID == who, 3:6]
  } else {
    ppds.master[i, 3:6] <- NA
  }
  if (male.TF) {
    ppds.master$gender[i] <- "M"
    ppds.master[i, 7:8] <- ppds.male[ppds.male$IDENT_SUBID == who, 3:4]
  } else {
    ppds.master[i, 7:8] <- NA
  }
}
```

Write out a csv
```{r}
#convert all data to character
ppds <- as.data.frame(lapply(ppds.master, as.character))
library(readr)
write_csv(ppds,"/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/03 Scored/csv/ppds_constructs_merged.csv")
```

