---
title: "PQ tidying"
author: "Ian Douglas"
date: "5/30/2019"
output: html_document
---
#load in raw data
```{r}
rm(list=ls())
suppressPackageStartupMessages(library(tidyverse))
df <- read.csv("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/01 Raw/QUALTRICS/PI/PQ raw.csv", stringsAsFactors = FALSE)
```
#View the ID field to examine fake/test ddata
```{r}
df$Q1[1:10] #real entries begin on line 2
tail(df$Q1) #no fake data
```
#Extract desired data
```{r}
df1 <- df[-1:-2,] %>% dplyr::select(RecordedDate, starts_with("Q"))
```
#Search for duplicates in theID field
```{r}
#First see, if any entries contain all letters
where<-all.letters(df1$Q1)
# [1] 23
df2 <- df1[-where,]#remove the entry
View(id.search(df2, "Q1", "RecordedDate"))
```
#index entries to delete
```{r}
ids.to.remove <- c(
  which(df2$Q1 == "097" & df2$RecordedDate == "2017-05-30 11:30:18"), #missingness
  which(df2$Q1 == "El122" & df2$RecordedDate == "2018-05-03 17:03:35"), # missingness
  which(df2$Q1 == "EL104" & df2$RecordedDate == "2018-06-13 17:45:17"),#missingness
  which(df2$Q1 == "EL105" & df2$RecordedDate == "2018-06-13 17:46:31")
)
#FIRST:
#take the last three columns from the above entry and merge it with the correct one.
df2[which(df2$Q1 == "EL105" & df2$RecordedDate == "2018-05-29 16:31:25"), 22:25] <-
df2[which(df2$Q1 == "EL104" & df2$RecordedDate == "2018-06-13 17:45:17"), 22:25]
#Next, delete the unwanted rows
df3 <- df2[-ids.to.remove,]
#lastly, swith the subject ID for 104 and 105, whose (retained) entries switched the subject ID
df3$Q1[c(grep("104", df3$Q1),grep("105", df3$Q1))] <- c("EL105", "EL104")
```
#Format subject ID and date columns
```{r}
df4 <- df3 %>% ELFK.identsubid("Q1") %>% format.date("RecordedDate")
```
#Add in the variable names
```{r}
#first create an empty column
df5 <- data.frame(df4[1:5],"PQ_3_AGEFOSTER" = NA_integer_, df4[6:ncol(df4)])
#create the list of variable names in the correct order
vnam <- c("PQ_DATE_COMPLETE", "IDENT_SUBID",
          "PQ_1_COUNTRYBORN", "PQ_2_CITYBORN", "PQ_3_AGEORPH", 
          "PQ_3_AGEFOSTER","PQ_4_AGEADOPT","PQ_5_GENHEALTHADOPT",
          "PQ_6A_GROCHART","PQ_6B_PERCENTILE","PQ_7A_HEALTHCONS",
          "PQ_7B_EXPLAN","PQ_8A_BEHCONS","PQ_8B_EXPLAN",
          "PQ_9_STRENGTH", "PQ_10A_HEALTHCONS_OVERC", "PQ_10B_EXPLAN",
          "PQ_11A_BEHACONS_OVERC","PQ_11B_EXPLAN","PQ_12A_OTHERCHILD",
          "PQ_12B_AGEOTHERCH","PQ_12C_ADOPTORBIOCH","PQ_13_MOTIVADOPT",
          "PQ_14A_TALKADOSTORY","PQ_14B_CHENJOYADSTORY","PQ_14C_PENJOYADSTORY")
names(df5) <- vnam
```
#For select subjects
merge in their data from older versions of the form
```{r}
ageorph.merge <- #5
agefost.merge <- #6
ageadopt.merge <- #7
behcons.merge <- #13
explan.8b.merge <- #14
healthcons.10a.merge <- #16
behacons.merge <- #18
explan.11b.merge <- #19
adoptorbio.merge <- #22
```

