---
title: "SCARED tidying"
author: "Ian Douglas"
date: "3/11/2019"
output: html_document
---
###Data exported from qualtrics 3/11/2019
#load data
```{r}
# library(tidyverse)
rm(list=ls())
df <- read.csv("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/01 Raw/QUALTRICS/Parent/SCARED raw.csv", stringsAsFactors = FALSE)
```

#real data starts on line 9
```{r}
df1 <- df[-1:-8,] %>% select(RecordedDate, starts_with("Q"))
```
#search for duplicates
```{r}
View(id.search(df1,"Q3","RecordedDate"))
```
#results of the search
```{r}
#"EL041P" is actually "EL042"
df1$Q3[grep("EL041P", df1$Q3)]<- "EL042"
df1$Q3[grep("EL016_2", df1$Q3)] <- "EL016" #determined from Michelle L's notes
df1$Q3[grep("el06lp",df1$Q3)] <- "EL061" #determined from discussion with Tricia C
#delete the following as a result of the corrections.
rm.i1<-which(df1$RecordedDate == "2017-04-04 12:55:37" & df1$Q3 == "098")
rm.i2 <- which(df1$RecordedDate == "2018-01-05 14:07:04" & df1$Q3 == "EL127")
rm.i3 <- which(df1$Q3 == "EL104" & df1$RecordedDate == "2018-06-04 17:30:53")
rm.i4 <- which(df1$Q3 == "EL144" & df1$RecordedDate == "2018-08-22 00:12:24")
rm.i5 <- which(df1$Q3 == "EL042" & df1$RecordedDate == "2018-05-22 07:45:40")
rm.i6 <- which(df1$RecordedDate == "2018-08-09 19:19:18" & df1$Q3 == "EL061")
rm.i7<-which(df1$RecordedDate=="2016-03-25 15:14:51" & df1$Q3 == "EL016")
df2 <- df1[-c(rm.i1,rm.i2,rm.i3,rm.i4,rm.i5,rm.i6,rm.i7),]
```
#Format the date and standardize subject ID column
```{r}
df3 <- df2 %>% ELFK.identsubid("Q3") %>% format.date("RecordedDate")
```

###Rename columns
```{r}
var.names <- c("SCARED_DATE_COMPLETE", "IDENT_SUBID", "SCARED_1", "SCARED_2", 
               "SCARED_3", "SCARED_4","SCARED_5","SCARED_6","SCARED_7","SCARED_8",
               "SCARED_9","SCARED_10","SCARED_11","SCARED_12",
               "SCARED_13","SCARED_14","SCARED_15","SCARED_16",
               "SCARED_17","SCARED_18","SCARED_19","SCARED_20",
               "SCARED_21","SCARED_22","SCARED_23","SCARED_24",
               "SCARED_25","SCARED_26","SCARED_27","SCARED_28",
               "SCARED_29","SCARED_30","SCARED_31","SCARED_32",
               "SCARED_33","SCARED_34","SCARED_35","SCARED_36",
               "SCARED_37", "SCARED_38","SCARED_39","SCARED_40","SCARED_41")
names(df3) <- var.names
```

###Now convert data to numeric
```{r}
df4 <- df3 %>% mutate_at(-1:-2, as.numeric)
```

###Recode the numeric variables
```{r}
#Qualtrics output the data on a range from 1 to 3 rather than 0 to 2
df5 <- df4
df5[,3:42] <- lapply(df5[,3:42], function(x) (x - 1))
```

#finally, one mock test data produced "EL999"
```{r}
removal <- grep("999", df5$IDENT_SUBID)
df6 <- df5[-removal,]
```

##Tidying Complete!
###Write out tidy .Rds, csv and sav files.
```{r}
write_rds(df6,"/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/02 Tidied/QUALTRICS/Parent/SCARED_tidy.Rds")
library(haven)
#convert all fields to character for csv and sav write-out
df7 <- as.data.frame(lapply(df6[,1:42], function(x) as.character(x)),
                     stringsAsFactors = F)
write.csv(df7, "/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/02 Tidied/QUALTRICS/Parent/SCARED_tidy.csv", row.names = FALSE)
write_sav(df7, "/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/02 Tidied/QUALTRICS/Parent/SCARED_tidy.sav")
```

