---
title: "STAI State tidying"
author: "Ian Douglas"
date: "5/29/2019"
output: html_document
---
#load raw data, extracted 5/29/19
```{r}
rm(list=ls())
suppressPackageStartupMessages(library(tidyverse))
df <- read.csv("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/01 Raw/QUALTRICS/Parent/STAI State raw.csv", stringsAsFactors = FALSE)
```

#Check for mock/test data
```{r}
df$Q1[1:15] #real data begins on line 9
tail(df$Q1) #none found here
```
Extract desired data. NOTE: the questions erroneously repeated themselves, such that questions "Q4_21" through "Q4_40" are a repeat of the first 20 questions.
```{r}
df1 <- df[-1:-8, c("RecordedDate","Q1", #skip user-entered date, age, and sex
                   names(df)[
                     grep("^Q4_1$", names(df)):grep("^Q4_20$",names(df))
                     ])]
```
#search for duplicates
```{r}
View(id.search(df1, "Q1", "RecordedDate"))
#Error in View : There are no duplicates
#Done!
```

#format the subject ID and date columns
```{r}
df2 <- ELFK.identsubid(df1, "Q1") %>% 
  format.date("RecordedDate")
```
#attach the proper variable names
```{r}
df3 <- df2
vnam <- NULL
for (i in 1:20) {
  vnam[i]<- paste0("PARENT_STAI_STATE_",i)
}
names(df3) <- c("PARENT_STAI_STATE_DATE","IDENT_SUBID",vnam)
```
#ensure numeric data are in correct form
```{r}
# > get.variable.classes(df3)
# classes
# character      Date 
#        23         1 
#convert numeric variables to appropriate format
df4 <- df3 %>%
  mutate_at(-1:-2, as.numeric)
```
Done!
Write out tidy data
```{r}
saveRDS(df4, "/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/02 Tidied/QUALTRICS/Parent/R/STAI_state_tidy.rds")
```
