---
title: "DSM parent report tidying"
author: "Ian Douglas"
date: "5/31/2019"
output: html_document
---
#load in raw data
```{r}
rm(list=ls())
df.dsm <- read.csv("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/01 Raw/QUALTRICS/Parent/DSM_P.csv", stringsAsFactors = FALSE)
```
#view subject id column
```{r}
df$Q1[1:10] #real data starts on row 3
tail(df$Q1) #remove "EL###"
rows.to.remove <- c(1:2, grep("EL###", df$Q1))
```
#Extract desired data
```{r}
#also delete user-entered date
df1 <- df[-rows.to.remove,] %>% select(RecordedDate, starts_with("Q"), -Q4)
```
#search for duplicate entries
```{r}
View(id.search(df1, "Q1", "RecordedDate"))
```
#based on date of scan, EL091 mis-entered their ID (they are actually EL092)
```{r}
df1[df1$Q1 %in% "EL091", "Q1"] <- "EL092"
#remove the duplicate of 144 that was generated when the parent went back in (months later) to fill out the forms for the sibling (for whom there is no duplicate)
df2 <- df1[-which(df1$Q1 %in% "EL144" & df1$RecordedDate %in% "2018-08-22 00:29:42"),]
```
#Format the date and subject ID columns
```{r}
df3 <- df2 %>% ELFK.identsubid("Q1") %>% format.date("RecordedDate")
```
#Recode from qualtrics output (no subscale variables to create)
```{r}
#1. Adjust the range of questions to 0 to 3, rather than 1 to 4.
shift.range <- function(x) {x-1}
#2. Recode Yes/No so that it goes from 1 and 2 to--> 1 and 0 
fix.binary <- function(x) {sub(2,0,x)}
df4 <- df3 %>% 
  mutate_at(grep("Q6_", names(.)), function(x) shift.range(as.numeric(x))) %>%
  mutate_at(grep("Q7_", names(.)), function(x) as.numeric(fix.binary(as.numeric(x)))) %>%
  mutate_at(3:4, as.numeric) %>% #3. also create numeric variables for gender and age
  mutate_at(4, function(x) (x - 1)) #4. recode M/F from 1 and 2 to--> 0 and 1.
```
#Attach the variable names
```{r}
item.names <- c()
for (i in 1:(ncol(df4)-4)) {
  item.names <- c(item.names, paste0("DSM_", i, "_P"))
}
vnam <- c("DSM_DATE_P", "IDENT_SUBID", "DSM_CHILD_AGE_P", "DSM_CHILD_GENDER_P",
          item.names)
names(df4) <- vnam
```
Done!
Write out tidy data
```{r}
saveRDS(df4,"/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/02 Tidied/QUALTRICS/Parent/R/DSM_P_tidy.rds")
```




