---
title: "CHILD_GRIT"
author: "Ian Douglas"
date: "2/25/2019"
output: html_document
---

CHILD_GRIT data processing
Produced by Ian Douglas

###Load data
```{r}
df <- read.csv("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/Raw/QUALTRICS/Qualtrics_Raw_Grit_Questionnaire.csv")
```

#Extract relevant information
```{r}
#View(df)
# Select variables of interest (supplant user-entered date with "RecordedDate")
df1 <- df %>% select(RecordedDate,starts_with("Q"),-Q13) 
#remove rows with fake data and qualtrics artifacts
df1 <- df1[6:nrow(df1),]
# remove participants who entered missing or uninterpretable ID #s
df1 <- df1[c(as.numeric(which(df1$Q12 == ""))*-1),]
df1 <- df1[c(as.numeric(which(df1$Q12 == "rty"))*-1),]
#Check dimensions (rows and columns should be 126 and 10 respectively)
dim(df1)
```
#Standardize subject ID numbers
```{r}
#Change variable from factor to character
df2 <- df1 %>%
  # extract id NUMBERS only
  mutate(Q12 = as.integer(str_extract(df1$Q12, 
                                         pattern ="\\(?[0-9,.]+\\)?")))%>%
  # add prefix "EL00", "EL0", or "EL" as necessary; rename:
  mutate(IDENT_SUBID = paste0(ifelse(nchar(Q12)==1,"EL00",
                                ifelse(nchar(Q12)==2,"EL0",
                                       "EL")), Q12)) %>%
  # remove old Q12 and return to desired order
  select(RecordedDate,IDENT_SUBID, everything(), -Q12)
```
#Rename variables
```{r}
var_names <- cbind("GRIT_DATE_COMPLETE_C", "IDENT_SUBID","GRIT_1_C", "GRIT_2_C",
                   "GRIT_3_C", "GRIT_4_C", "GRIT_5_C", "GRIT_6_C", "GRIT_7_C",
                   "GRIT_8_C")
names(df2) <- var_names
```

#Convert factors to numeric
```{r}
df3 <- df2
#Numeric Grit questionnaire responses begin with column 3, continue to the end of df
for (i in 3:ncol(df3)) {
  df3[i] <- as.numeric(as.character(df3[,i]))
}
```

#Reverse-code select variables
```{r}
#Create new variables (with reverse codes)
df4 <- df3 %>% mutate(GRIT_2_Cr = 6 - GRIT_2_C, GRIT_4_Cr = 6 - GRIT_4_C, 
                      GRIT_7_Cr = 6 - GRIT_7_C, GRIT_8_Cr = 6 - GRIT_8_C) %>%
  #return to original order, exclude old version of recoded questions
  select("GRIT_DATE_COMPLETE_C", "IDENT_SUBID","GRIT_1_C", "GRIT_2_Cr",
                   "GRIT_3_C", "GRIT_4_Cr", "GRIT_5_C", "GRIT_6_C", "GRIT_7_Cr",
                   "GRIT_8_Cr") %>% 
  #compute new variable for the mean
  mutate(GRIT_CHILD_MEAN_W1 = mean(c(GRIT_1_C, GRIT_2_Cr, GRIT_3_C, GRIT_4_Cr,
                                   GRIT_5_C,GRIT_6_C, GRIT_7_Cr, GRIT_8_Cr)))
```

#Write and save .csv and .sav
```{r}
write.csv(df4, "/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/Processed/Qualtrics_Cleaned_in_R_Child_GRIT_Questionnaire.csv", row.names = F)
#library(haven)
write_sav(df4, "/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/Processed/Qualtrics_Cleaned_in_R_Child_GRIT_Questionnaire.sav")
```
