---
title: "CRPR"
author: "Ian Douglas"
date: "3/6/2019"
output: html_document
---
# Produced by Ian Douglas
   
###Extract Data
```{r}
df <- read.csv("/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/Raw/QUALTRICS/Qualtrics_RAW_CRPR_Questionnaire.csv")
```  
   
#View data 
```{r}
#View data
View(df)
#Looks like real data starts with row 9: exract relevant rows and columns,
# and remove the subject-entered date field, retain qualtrics timestamp.
df1 <- df[9:nrow(df),] %>% select(RecordedDate,starts_with("Q"), -Q1_2)
```
   
  #Standardize subject ID's to ELFK format    
  
#Clean up some duplicate/erroneous entries  
```{r}
# Convert the subject ID variable to character first:
df1[,2]<-lapply(df1[2], as.character)
# Search for abnormally long entries:
df1$Q1_1[which(nchar(as.character(df1$Q1_1)) >
                 mean(nchar(as.character(df1$Q1_1))) +
                 sd(nchar(as.character(df1$Q1_1))))]
# [1] "EL044_P"         "EL036_P"         "EL056_P"         "EL102P "        
# [5] "EL104 and EL105"
```

```{r}
#After discussion with Michelle V. and Tricia C., duplicate the entry
df1<-rbind(df1,filter(df1,Q1_1=="EL104 and EL105"))

#Now before extracting ID numbers, make sure one of the duplicates contains
# "EL104" and the other "EL105"
i <- which(df1$Q1_1=="EL104 and EL105")
df1$Q1_1[i[1]] <- "EL104"
df1$Q1_1[i[2]] <- "EL105"
```

#correct the typo for subject "EL061"
```{r}
df1$Q1_1[which(df1$Q1_1=="elo6lp")] <- "EL061"
```
#Remove a duplicate for subject


#Now standardize the ID numbers
```{r}
df2 <- df1 %>%
  # extract id NUMBERS only
  mutate(Q1_1 = as.integer(str_extract(df1$Q1_1, 
                                         pattern ="\\(?[0-9,.]+\\)?")))%>%
  # add prefix "EL00", "EL0", or "EL" as necessary; rename:
  mutate(IDENT_SUBID = paste0(ifelse(nchar(Q1_1)==1,"EL00",
                                ifelse(nchar(Q1_1)==2,"EL0",
                                       "EL")), Q1_1)) %>%
  # remove old Q1_1 and return to desired order
  select(RecordedDate,IDENT_SUBID, everything(), -Q1_1)
```
   
   
#Convert numeric variables from factor to numeric.
```{r}
factor2numeric <- function(x) {as.numeric(as.character(x))}
df3 <- df2 %>% mutate_at(vars(starts_with("Q")),factor2numeric)
```
   
   
#Attach variable names
```{r}
var.names <- cbind("CRPR_DATE_COMPLETE","IDENT_SUBID", "CRPR_1", 
                   "CRPR_2", "CRPR_3", "CRPR_4", "CRPR_5", "CRPR_6", 
                   "CRPR_7", "CRPR_8","CRPR_9", "CRPR_10", "CRPR_11", 
                   "CRPR_12", "CRPR_13", "CRPR_14", "CRPR_15", "CRPR_16",
                   "CRPR_17","CRPR_18", "CRPR_19", "CRPR_20", "CRPR_21",
                   "CRPR_22", "CRPR_23", "CRPR_24", "CRPR_25", "CRPR_26",
                   "CRPR_27", "CRPR_28", "CRPR_29", "CRPR_30", "CRPR_31",
                   "CRPR_32", "CRPR_33", "CRPR_34", "CRPR_35",
                   "CRPR_36", "CRPR_37", "CRPR_38", "CRPR_39", "CRPR_40")
names(df3) <- var.names 
```
   
   #Code the two subscales
```{r}
df4 <- df3 %>%
  group_by(IDENT_SUBID) %>%
  mutate(CRPR_RESTRICT_MEAN = mean(c(CRPR_1, CRPR_2, CRPR_3, CRPR_6,
                                     CRPR_10, CRPR_12,CRPR_14, CRPR_15,
                                     CRPR_16,CRPR_22, CRPR_27, CRPR_28,
                                     CRPR_29, CRPR_31, CRPR_32,CRPR_33,
                                     CRPR_34, CRPR_35,CRPR_36, CRPR_37, 
                                     CRPR_38, CRPR_40),na.rm = TRUE),
         CRPR_NURTURE_MEAN = mean(c(CRPR_4, CRPR_5, CRPR_7, CRPR_8,
                                    CRPR_9, CRPR_11, CRPR_13,CRPR_17, 
                                    CRPR_18, CRPR_19,CRPR_20, CRPR_21, 
                                    CRPR_23,CRPR_24, CRPR_25, CRPR_26,
                                    CRPR_30, CRPR_39),na.rm=TRUE))
```

#Write out the csv and sav files.
```{r}
write.csv(df4, "/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/Processed/Qualtrics_Cleaned_in_R_CRPR_Questionnaire.csv", row.names = F)
#library(haven)
write_sav(df4, "/Volumes/danl/ELFK/Data_Entry/DATA_ENTRY_MASTER/Data_Merge/Processed/Qualtrics_Cleaned_in_R_CRPR_Questionnaire.sav")
```